import { getServerSession } from "next-auth";  
import { authOptions } from "@/lib/auth";  
import { redirect } from "next/navigation";
import PageHeader from "@/components/page-header";  
import SessionWrapper from "@/components/session-wrapper";  
import ThemeProvider from "@/components/ThemeProvider"; // Import ThemeProvider  
import "./globals.css";  
  
export const metadata = {  
  title: "Create Next App",  
  description: "Generated by create next app",  
};  
  
export default async function RootLayout({
  children,  
}: Readonly<{ children: React.ReactNode }>) {  
  const session = await getServerSession(authOptions);  
  
  return (  
    <html lang="en">  
      <body className="antialiased">  
        <ThemeProvider> {/* Wrap everything with ThemeProvider */}  
          <SessionWrapper>  
            <PageHeader />  
            {children}  
          </SessionWrapper>  
        </ThemeProvider>  
      </body>  
    </html>  
  );  
}